Form/DealerType.php
<?php

namespace Xngage\Bundle\DealersBundle\Form;

use Oro\Bundle\AddressBundle\Form\EventListener\AddressCountryAndRegionSubscriber;
use Oro\Bundle\AddressBundle\Form\Type\CountryType;
use Oro\Bundle\AddressBundle\Form\Type\RegionType;
use Oro\Bundle\FormBundle\Form\Type\CheckboxType;
use Symfony\Component\Form\AbstractType;
use Oro\Bundle\AttachmentBundle\Form\Type\ImageType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Oro\Bundle\FormBundle\Form\Extension\StripTagsExtension;
use Oro\Bundle\FormBundle\Form\Type\OroRichTextType;
use Oro\Bundle\LocaleBundle\Form\Type\LocalizedFallbackValueCollectionType;
use Oro\Bundle\RedirectBundle\Form\Type\LocalizedSlugWithRedirectType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Xngage\Bundle\DealersBundle\Entity\Dealer;
use Xngage\Bundle\DealersBundle\Entity\DealerDescription;
use Xngage\Bundle\DealersBundle\Entity\DealerTitle;
use Oro\Bundle\WebsiteBundle\Entity\Website;

class DealerType extends AbstractType
{
    /**
     * @var AddressCountryAndRegionSubscriber
     */
    private $countryAndRegionSubscriber;

    /**
     * @var UrlGeneratorInterface
     */
    protected $urlGenerator;

    public function __construct(
        AddressCountryAndRegionSubscriber $eventListener,
        UrlGeneratorInterface $urlGenerator
    ) {
        $this->countryAndRegionSubscriber = $eventListener;
        $this->urlGenerator = $urlGenerator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventSubscriber($this->countryAndRegionSubscriber);

        $builder
            ->add('websites', EntityType::class, [
                'class' => Website::class,
                'label' => "Enabled Websites",
                'multiple' => true,
                'required' => false
            ])
            ->add('active', CheckboxType::class, [
                'required' => true
            ])
            ->add('phone', TextType::class)
            ->add('erpId',  TextType::class, [
                'required' => false
            ])
            ->add('website_url',  TextType::class)
            ->add('hours', TextType::class)
            ->add(
                'titles',
                LocalizedFallbackValueCollectionType::class,
                [
                    'label' => 'Titles',
                    'required' => true,
                    'value_class' => DealerTitle::class,
                    'entry_options' => ['constraints' => [
                        new NotBlank(['message' => 'Dealer Title should not be blank.'])]
                    ],
                ]
            )
            ->add(
                'descriptions',
                LocalizedFallbackValueCollectionType::class,
                [
                    'label' => 'Descriptions',
                    'required' => false,
                    'value_class' => DealerDescription::class,
                    'field' => 'text',
                    'entry_type' => OroRichTextType::class,
                    'entry_options' => [
                        'wysiwyg_options' => [
                            'autoRender' => false,
                            'elementpath' => true,
                            'resize' => true,
                            'height' => 200,
                        ],
                    ],
                    'use_tabs' => true,
                ]
            )
            ->add(
                'image1',
                ImageType::class,
                [
                    'label'    => 'Image 1',
                    'required' => false
                ]
            )
            ->add(
                'image2',
                ImageType::class,
                [
                    'label'    => 'Image 2',
                    'required' => false
                ]
            )
            ->add(
                'image3',
                ImageType::class,
                [
                    'label'    => 'Image 3',
                    'required' => false
                ]
            )
            ->add(
                'slugPrototypesWithRedirect',
                LocalizedSlugWithRedirectType::class,
                [
                    'label'    => 'URL Slug',
                    'required' => false,
                    'source_field' => 'titles',
                    'allow_slashes' => true,
                ]
            )
            ->add('address', TextType::class)
            ->add('address2', TextType::class)
            ->add('country', CountryType::class, array('required' => true, 'label' => 'oro.address.country.label'))
            ->add('city', TextType::class, array(
                'required' => false,
                'label' => 'oro.address.city.label',
                StripTagsExtension::OPTION_NAME => true,
            ))
            ->add('region', RegionType::class, array('required' => false, 'label' => 'oro.address.region.label'))
            ->add('postalCode', TextType::class, array(
                'required' => false,
                'label' => 'oro.address.postal_code.label',
                StripTagsExtension::OPTION_NAME => true,
            ))
            ->add(
                'region_text',
                HiddenType::class,
                array('required' => false, 'random_id' => true, 'label' => 'oro.address.region_text.label')
            )
            // Manager Info
            ->add('managerName', TextType::class)
            ->add('managerTitle', TextType::class)
            ->add('managerCellPhone', TextType::class)
            ->add('managerEmail', TextType::class)
            ->add('managerOfficePhone', TextType::class)
            ->add('latlng', GoogleMapsPickerType::class)
            ->add(
                'managerImage',
                ImageType::class,
                [
                    'label'    => 'Manager Image',
                    'required' => false
                ]
            )->addEventListener(FormEvents::PRE_SET_DATA, [$this, 'preSetDataListener']);
    }

    public function preSetDataListener(FormEvent $event)
    {
        $dealer = $event->getData();

        if ($dealer instanceof Dealer && $dealer->getId()) {
            $url = $this->urlGenerator->generate(
                'xngage_dealer_get_changed_slugs',
                ['id' => $dealer->getId()]
            );

            $event->getForm()->add(
                'slugPrototypesWithRedirect',
                LocalizedSlugWithRedirectType::class,
                [
                    'label'    => 'URL Slug',
                    'required' => false,
                    'get_changed_slugs_url' => $url,
                    'source_field' => 'titles',
                    'allow_slashes' => true,
                ]
            );
        }
    }
}

Form/GoogleMapsPickerType.php
<?php 

namespace Xngage\Bundle\DealersBundle\Form;

use Oro\Bundle\ConfigBundle\Config\ConfigManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class GoogleMapsPickerType extends AbstractType
{
    /**
     * @var ConfigManager
     */
    protected $configManager;

    /**
     * GoogleMapsPickerType constructor.
     *
     * @param ConfigManager $manager
     */
    public function __construct(ConfigManager $manager)
    {
        $this->configManager = $manager;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Optional Address field
        if (isset($options['addr_name']) && $options['addr_name']) {
            $builder->add($options['addr_name'], $options['addr_type'], array_merge($options['options'], $options['addr_options']));
        }

        // Default fields: latitude, longitude
        $builder
            ->add($options['lat_name'], $options['type'], array_merge($options['options'], $options['lat_options']))
            ->add($options['lng_name'], $options['type'], array_merge($options['options'], $options['lng_options']));

        // Optional Address field use button
        if (isset($options['addr_use_btn']) && $options['addr_use_btn']) {
            $builder->add(
                $options['addr_use_btn']['name'], ButtonType::class,
                array_merge(
                    $options['options'], isset($options['addr_use_btn']['options']) ? $options['addr_use_btn']['options'] : []
                )
            );
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'api_key'          => $this->configManager->get('oro_google_integration.google_api_key'),
            'type'             => TextType::class, // the types to render the lat and lng fields
            'addr_type'        => HiddenType::class, // the type to render the address field
            'attr'             => ['class' => 'form-group'],
            'search_enabled'   => true,
            'options'          => [], // the options for both the fields
            'lat_options'      => [], // the options for just the lat field
            'lng_options'      => [], // the options for just the lng field
            'addr_options'     => [], // the options for just the address field
            'addr_use_btn'     => [], // the options for the address use button
            'lat_name'         => 'lat', // the name of the lat field
            'lng_name'         => 'lng', // the name of the lng field
            'addr_name'        => 'address', // the name of the addr field
            'error_bubbling'   => false,
            'map_width'        => '100%', // the width of the map
            'map_height'       => '400px', // the height of the map
            'default_lat'      => $this->configManager->get('xngage_dealers.default_latitude', 41.390205), // the starting position on the map
            'default_lng'      => $this->configManager->get('xngage_dealers.default_longitude', 2.154007), // the starting position on the map
            'include_jquery'   => true, // jquery needs to be included above the field (ie not at the bottom of the page)
            'include_gmaps_js' => true     // is this the best place to include the google maps javascript?
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['api_key']          = $options['api_key'];
        $view->vars['search_enabled']   = $options['search_enabled'];
        $view->vars['lat_name']         = $options['lat_name'];
        $view->vars['lng_name']         = $options['lng_name'];
        $view->vars['addr_name']        = $options['addr_name'] ?: null;
        $view->vars['addr_use_btn']     = $options['addr_use_btn'] ?: [];
        $view->vars['map_width']        = $options['map_width'];
        $view->vars['map_height']       = $options['map_height'];
        $view->vars['default_lat']      = $options['default_lat'];
        $view->vars['default_lng']      = $options['default_lng'];
        $view->vars['include_jquery']   = $options['include_jquery'];
        $view->vars['include_gmaps_js'] = $options['include_gmaps_js'];
    }

    public function getParent()
    {
        return FormType::class;
    }

    public function getName()
    {
        return 'xngage_google_maps_picker';
    }

    public function getBlockPrefix()
    {
        return 'xngage_google_maps_picker';
    }
}

Form/Validator/Constraints/LatLng.php
<?php

namespace Xngage\Bundle\DealersBundle\Form\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class LatLng extends Constraint
{
    public $message = 'The values for latitude and longitude ("%lat%" and "%lng%") are not valid.';
}

Form/Validator/Constraints/LatLngValidator.php
<?php

namespace Xngage\Bundle\DealersBundle\Form\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class LatLngValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {
        if (!preg_match('/^[0-9\-\.]+$/', $value['lat'], $matches) || !preg_match('/^[0-9\-\.]+$/', $value['lng'], $matches)) {
            $this->context->addViolation($constraint->message, array('%lat%' => (float)$value['lat'], '%lng%' => (float)$value['lng']));
            return false;
        }
        if($value['lat'] > 90 || $value['lat'] < -90 || $value['lng'] > 180 || $value['lng'] < -180)
        {
            $this->context->addViolation($constraint->message, array('%lat%' => (float)$value['lat'], '%lng%' => (float)$value['lng']));
            return false;
        }

        return true;
    }
}

Resources/views/Form/fields.html.twig
{% block xngage_google_maps_picker_widget %}
    <div {{ block('widget_container_attributes') }}>
        {% block xngage_google_maps_fields %}
            {% for child in form %}
                {{ form_row(child) }}
            {% endfor %}
        {% endblock %}
        {% block xngage_google_maps_html %}
            <div id="{{ id }}_container" class="form-group">
                {% if search_enabled %}
                    <div class="input-group">
				<span class="input-group-btn">
					<a href="#" id="{{ id }}_current_position" class="btn btn-default">{{ "Goto current location"|trans }}</a>
				</span>
                        <input type="text" id="{{ id }}_input" class="form-control" placeholder="{{ 'Find address'|trans }}" aria-label="{{ 'Find address'|trans }}" aria-describedby="basic-addon2">
                        <span class="input-group-btn">
					<button id="{{ id }}_search_button" class="btn btn-primary" type="button">{{ "Search"|trans }}</button>
				</span>
                    </div>
                {% else %}
                    <p>
                        <a href="#" id="{{ id }}_current_position" class="btn btn-default">{{ "Goto current location"|trans }}</a>
                    </p>
                {% endif %}

                <div id="{{ id }}_map_canvas" class="gmap" style="width: {{ map_width }}; height: {{ map_height }};margin-top: 10px"></div>
                <div id="{{ id }}_error"></div>
            </div>
        {% endblock %}
        {% block xngage_google_maps_javascripts %}

            {% if include_jquery %}
            <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
            {% endif %}

            {% if include_gmaps_js %}
            <script async defer type="text/javascript" src="//maps.google.com/maps/api/js?key={{ api_key }}&callback=initMap"></script>
            {% endif %}

        {% endblock %}
        {% block xngage_google_maps_javascript %}
        {% block xngage_google_maps_callback %}
            <script type="text/javascript">
                var xngage_google_maps_callback = function(location, gmap){
                    // your callback function here
                }
            </script>
        {% endblock %}
            <script type="text/javascript">
                function initMap() {

                    $.loadScript = function (url, callback) {
                        $.ajax({
                            url: url,
                            dataType: 'script',
                            success: callback,
                            async: true
                        });
                    }
                    $.loadScript('/bundles/xngagedealers/js/jquery.xngage.googlemaps.js', function(){
                        $('.control-group-xngage_google_maps_picker .control-label:first').remove();
                        $('.control-group-xngage_google_maps_picker .controls:first').css('margin-left', 0)
                        // Set xngageGoogleMapType
                        $('#{{ id }}_map_canvas').xngageGoogleMapType({
                            'search_input_el'    : $('#{{ id }}_input'),
                            'search_action_el'   : $('#{{ id }}_search_button'),
                            'search_error_el'    : $('#{{ id }}_error'),
                            'current_position_el': $('#{{ id }}_current_position'),
                            'default_lat'        : '{% if value is defined and value and attribute(value, lat_name) %}{{ attribute(value, lat_name) }}{% else %}{{ default_lat }}{% endif %}',
                            'default_lng'        : '{% if value is defined and value and attribute(value, lng_name) %}{{ attribute(value, lng_name) }}{% else %}{{ default_lng }}{% endif %}',
                            'default_zoom'       : {% if value is defined and value and value.lat and value.lng %}15{% else %}5{% endif %},
                            'lat_field'          : $('#{{ attribute(form, lat_name).vars.id }}'),
                            'lng_field'          : $('#{{ attribute(form, lng_name).vars.id }}'),
                            {% if addr_name is defined and addr_name and attribute(form, addr_name) %}
                            'addr_field'         : $('#{{ attribute(form, addr_name).vars.id }}'),
                            {% endif %}
                            {% if addr_use_btn is defined and addr_use_btn and attribute(form, addr_use_btn.name) %}
                            'addr_use_btn'       : $('#{{ attribute(form, addr_use_btn.name).vars.id }}'),
                            {% endif %}
                            'callback'           : xngage_google_maps_callback
                        });
                        // Set use_btn behaviour
                        {% if addr_use_btn is defined and addr_use_btn and attribute(form, addr_use_btn.name) %}
                        $('#{{ attribute(form, addr_use_btn.name).vars.id }}').on('click', function(){
                            $('#{{ form.parent.offsetGet( addr_use_btn.target ).vars.id }}').val(
                                $('#{{ attribute(form, addr_name).vars.id }}').val()
                            );
                        });
                        {% endif %}
                    });
                }
            </script>
        {% endblock %}
    </div>
{% endblock %}